In [1]:
import numpy as np

### BroadCasting in Python  

```
[m x n]  (+-\*/)  [1 x n]  ==>   [m x n]  (+-\*/)  [m x n]  
[m x n]  (+-\*/)  [m x 1]  ==>   [m x n]  (+-\*/)  [m x n]
```

In [2]:
arr = np.random.randint(0, 40, 9).reshape(3,3)
arr

array([[16, 13, 37],
       [ 7,  3, 39],
       [12,  4,  7]])

In [3]:
sum_arr = np.sum(arr, axis=0)  # adding sum column-wise
print(sum_arr)
print(sum_arr.reshape(1,3)) # better to convert the vector to 1x3 matrix

[35 20 83]
[[35 20 83]]


### Calculating the percentage

In [4]:
arr/sum_arr  # dividing each column element with particular value

array([[ 0.45714286,  0.65      ,  0.44578313],
       [ 0.2       ,  0.15      ,  0.46987952],
       [ 0.34285714,  0.2       ,  0.08433735]])

In [5]:
np.sum(arr/sum_arr, axis=0)

array([ 1.,  1.,  1.])

#### Some Examples

In [6]:
np.arange(0,4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [7]:
np.arange(0,4).reshape(4,1)  + 100   # (100 will be broadcasted as 4x1 matrix )

array([[100],
       [101],
       [102],
       [103]])

In [8]:
np.arange(0,4).reshape(2,2)  + np.array([100, 200])  # [100, 200] (1 row vector)  will broad casted as 2x2 matrix

array([[100, 201],
       [102, 203]])

In [9]:
np.arange(0,4).reshape(2,2)  + np.array([[100], [200]])   # [[100], [200]] (1 column vector)  will broad casted as 2x2 matrix

array([[100, 101],
       [202, 203]])

### Should be an error in Python

In [10]:
print(np.array([1,2,3]))
print(np.array([[1],[2],[3]]))

[1 2 3]
[[1]
 [2]
 [3]]


In [12]:
# 1 x 3   add 3 x 1 matrix can not be added but due to broadcasting 
np.array([1,2,3]) + np.array([[1],[2],[3]])     

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

To avoid this error, always convert array (rank 1) to proper matrix

In [13]:
a = np.random.randint(4, 10, 4)
a

array([6, 4, 7, 9])

In [14]:
a.shape  # rank 1 array

(4,)

In [15]:
np.dot(a, a.T)

182

In [16]:
a = np.random.randint(4, 10, (4,1))  # start, end, size
a

array([[4],
       [9],
       [5],
       [9]])

In [23]:
a.T

array([[4, 9, 5, 9]])

In [17]:
a.shape

(4, 1)

In [22]:
(a.T).shape

(1, 4)

### tips to avoid these kind of error  

** DO NOT use Rank 1 Vector **

In [ ]:
assert(a.shape == (4,1))

In [19]:
assert(a.shape == (4,2))

AssertionError: 

In [30]:
c = np.arange(1,5)
print(c)
print(c.shape)
print()
print(c.T)
print(c.T.shape)

[1 2 3 4]
(4,)

[1 2 3 4]
(4,)


In [28]:
np.dot(c, c.T)

30

In [32]:
a = np.arange(1,5).reshape(4,1)
b = np.arange(1,5).reshape(1,4)

print(a)
print(a.shape)
print()
print(b)
print(b.shape)
print()
print(np.dot(a,b))

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[1 2 3 4]]
(1, 4)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
