In [2]:
import numpy as np

### BroadCasting in Python  

```
[m x n]  (+-\*/)  [1 x n]  ==>   [m x n]  (+-\*/)  [m x n]  
[m x n]  (+-\*/)  [m x 1]  ==>   [m x n]  (+-\*/)  [m x n]
```

In [3]:
arr = np.random.randint(0, 40, 9).reshape(3,3)
arr

array([[12,  3,  9],
       [26, 31, 39],
       [25, 13, 20]])

In [4]:
sum_arr = np.sum(arr, axis=0)  # adding sum column-wise
print(sum_arr)
print(sum_arr.reshape(1,3)) # better to convert the vector to 1x4 matrix

[63 47 68]
[[63 47 68]]


In [5]:
arr/sum_arr  # dividing each column element with particular value

array([[ 0.19047619,  0.06382979,  0.13235294],
       [ 0.41269841,  0.65957447,  0.57352941],
       [ 0.3968254 ,  0.27659574,  0.29411765]])

In [6]:
arr/sum_arr.reshape(1,3)

array([[ 0.19047619,  0.06382979,  0.13235294],
       [ 0.41269841,  0.65957447,  0.57352941],
       [ 0.3968254 ,  0.27659574,  0.29411765]])

In [7]:
np.sum(arr/sum_arr, axis=0)

array([ 1.,  1.,  1.])

#### Some Examples

In [8]:
np.arange(0,4).reshape(4,1)  + 100   # (100 will be broadcasted as 4x1 matrix )

array([[100],
       [101],
       [102],
       [103]])

In [9]:
np.arange(0,4).reshape(2,2)  + np.array([100, 200])  # [100, 200] (1 row vector)  will broad casted as 2x2 matrix

array([[100, 201],
       [102, 203]])

In [10]:
np.arange(0,4).reshape(2,2)  + np.array([[100], [200]])   # [[100], [200]] (1 column vector)  will broad casted as 2x2 matrix

array([[100, 101],
       [202, 203]])

### Should be an error in Python

In [11]:
np.array([1,2,3]) + np.array([[1],[2],[3]])     # 1 x 3   add 3 x 1 matrix can not be added but due to broadcasting 

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

To avoid this error, always convert array (rank 1) to proper matrix

In [23]:
a = np.random.randint(4, 10, 4)
a

array([5, 8, 5, 4])

In [24]:
a.shape  # rank 1 array

(4,)

In [25]:
np.dot(a, a.T)

130

In [26]:
a = np.random.randint(4, 10, (4,1))  # start, end, size
a

array([[9],
       [4],
       [8],
       [4]])

In [27]:
a.shape

(4, 1)

In [33]:
assert(a.shape == (4,1))

In [34]:
assert(a.shape == (4,2))

AssertionError: 

In [28]:
np.dot(a, a.T)

array([[81, 36, 72, 36],
       [36, 16, 32, 16],
       [72, 32, 64, 32],
       [36, 16, 32, 16]])