In [22]:
# import
import random
import numpy as np
import time
import math

In [23]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]   # mutiply and sum
toc = time.time()
print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

249767.558973
Numpy method time:  69.99993324279785  ms
249767.558973
For loop method time:  813.9998912811279  ms


** Avoid For loops to do the calculations, Use Vectorization to do the task **

In [24]:
tic = time.time()
c = np.exp(a)
toc = time.time()
#print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = np.zeros((1000000, 1))  # creating zero array
tic = time.time()
for i in range(1000000):
    c[i] = math.exp(a[i])   # looping and calculation exp of value
toc = time.time()
#print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

Numpy method time:  32.000064849853516  ms
For loop method time:  763.9999389648438  ms


## Numpy Vector Operations

In [25]:
a = np.random.rand(2,3)
b = np.random.rand(3,4)
c = np.arange(10)
d = np.random.randint(0,100,10)

In [26]:
print(c)
print(d)
c*d  # element wise multiplication

[0 1 2 3 4 5 6 7 8 9]
[95 82 16 42 19 81 20 39  4  2]


array([  0,  82,  32, 126,  76, 405, 120, 273,  32,  18])

In [27]:
e=np.dot(a,b)  # matrix multiplication
print(a)
print(b)
print(e)

[[ 0.36862486  0.28471333  0.41136249]
 [ 0.38675478  0.01378155  0.70060816]]
[[ 0.60710616  0.8645525   0.42075561  0.99522569]
 [ 0.77427049  0.3385313   0.50334366  0.7548373 ]
 [ 0.05946259  0.69308777  0.43501834  0.14683187]]
[[ 0.46870024  0.70019023  0.47735985  0.6421783 ]
 [ 0.28713183  0.82461824  0.4744435   0.49818273]]


In [28]:
print(np.dot(d.T,c))
print(np.dot(c,d.T))
print(c.shape)
print((d.T).shape)

1164
1164
(10,)
(10,)


** Few functions supported **  

In [29]:
print(e)
print(np.log(e))  # log for each element
print(np.exp(e))  # exp value for each element
print(np.max(e))  # max value in matrix
print(np.max(e, axis=0))  # column wise
print(np.max(e, axis=1))  # row wise

[[ 0.46870024  0.70019023  0.47735985  0.6421783 ]
 [ 0.28713183  0.82461824  0.4744435   0.49818273]]
[[-0.75779187 -0.35640323 -0.73948466 -0.44288929]
 [-1.24781382 -0.19283474 -0.74561275 -0.69678835]]
[[ 1.59791593  2.01413581  1.61181336  1.90061648]
 [ 1.33259988  2.2810098   1.60711958  1.64572781]]
0.824618241525
[ 0.46870024  0.82461824  0.47735985  0.6421783 ]
[ 0.70019023  0.82461824]


In [30]:
print(e.T) # transpose the matrix

[[ 0.46870024  0.28713183]
 [ 0.70019023  0.82461824]
 [ 0.47735985  0.4744435 ]
 [ 0.6421783   0.49818273]]


In [32]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
a = 3  # 
print(np.binary_repr(a, width=8))
b=np.invert(a)   
print(np.binary_repr(b, width=8))
print(b)

00000011
11111100
-4


In [35]:
# flatten the matrix into one vector
m.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.dot(m, np.invert(m))

array([[ -18,  -21,  -24],
       [ -54,  -66,  -78],
       [ -90, -111, -132]])

In [45]:
A = np.matrix(np.arange(9).reshape(3,3))
A

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [46]:
np.linalg.norm(A)

14.282856857085701

In [50]:
# np.linalg.inv(A)   # this is a singular matrix as the determinant of this matrix is zero
np.linalg.det(A)

0.0

In [57]:
B = np.matrix(np.random.randint(1, 20, 9).reshape(3,3))
B

matrix([[ 9,  1, 18],
        [15, 13,  3],
        [13,  7, 12]])

In [58]:
# inverse matrix
C=np.linalg.inv(B)
C

matrix([[-1.73076923, -1.46153846,  2.96153846],
        [ 1.80769231,  1.61538462, -3.11538462],
        [ 0.82051282,  0.64102564, -1.30769231]])

In [59]:
np.dot(C, B)   # this will not generate an ideal identity matrix  [[1 0 0], [0 1 0], [0 0 1]]

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        [  3.55271368e-15,   0.00000000e+00,   1.00000000e+00]])

In [60]:
np.dot(B, C)  # 

matrix([[  1.00000000e+00,   0.00000000e+00,   3.55271368e-15],
        [ -8.88178420e-16,   1.00000000e+00,   1.33226763e-15],
        [ -3.55271368e-15,   8.88178420e-16,   1.00000000e+00]])