In [4]:
# import
import random
import numpy as np
import time
import math

In [5]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]   # mutiply and sum
toc = time.time()
print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

250330.285491
Numpy method time:  2.000093460083008  ms
250330.285491
For loop method time:  793.9999103546143  ms


** Avoid For loops to do the calculations, Use Vectorization to do the task **

In [6]:
tic = time.time()
c = np.exp(a)
toc = time.time()
#print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = np.zeros((1000000, 1))  # creating zero array
tic = time.time()
for i in range(1000000):
    c[i] = math.exp(a[i])   # looping and calculation exp of value
toc = time.time()
#print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

Numpy method time:  19.00005340576172  ms
For loop method time:  768.9998149871826  ms


## Numpy Vector Operations

In [7]:
a = np.random.rand(2,3)
b = np.random.rand(3,4)
c = np.arange(10)
d = np.random.randint(0,100,10)

In [8]:
print(c)
print(d)
c*d  # element wise multiplication

[0 1 2 3 4 5 6 7 8 9]
[ 7 96  6 81  5 80 34 13 59 97]


array([  0,  96,  12, 243,  20, 400, 204,  91, 472, 873])

In [9]:
e=np.dot(a,b)  # matrix multiplication
print(a)
print(b)
print(e)

[[ 0.27154379  0.47880907  0.85970525]
 [ 0.76672311  0.69471776  0.02390236]]
[[ 0.45053586  0.31542487  0.96116187  0.03014245]
 [ 0.89471775  0.67768978  0.31315365  0.54457864]
 [ 0.12963106  0.91598973  0.84505994  0.12512393]]
[[ 0.66218369  1.19761685  1.1374408   0.37650388]
 [ 0.97011106  0.73454098  0.97469735  0.40443013]]


In [10]:
print(np.dot(d.T,c))
print(np.dot(c,d.T))
print(c.shape)
print((d.T).shape)

2411
2411
(10,)
(10,)


** Few functions supported **  

In [19]:
print(e)
print(np.log(e))  # log for each element
print(np.exp(e))  # exp value for each element
print(np.max(e))  # max value in matrix
print(np.max(e, axis=0))  # column wise
print(np.max(e, axis=1))  # row wise

[[ 0.66218369  1.19761685  1.1374408   0.37650388]
 [ 0.97011106  0.73454098  0.97469735  0.40443013]]
[[-0.41221228  0.18033363  0.12878083 -0.97682691]
 [-0.03034472 -0.30850949 -0.02562827 -0.9052763 ]]
[[ 1.93902194  3.31221401  3.11877658  1.4571812 ]
 [ 2.63823744  2.08452493  2.65036495  1.49844833]]
1.19761685183
[ 0.97011106  1.19761685  1.1374408   0.40443013]
[ 1.19761685  0.97469735]


In [20]:
print(e.T) # transpose the matrix

[[ 0.66218369  0.97011106]
 [ 1.19761685  0.73454098]
 [ 1.1374408   0.97469735]
 [ 0.37650388  0.40443013]]


In [21]:
print(np.in(e))   # inverse of matrix

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''