In [1]:
# import
import random
import numpy as np
import time
import math

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]   # mutiply and sum
toc = time.time()
print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

250031.724836
Numpy method time:  29.002904891967773  ms
250031.724836
For loop method time:  629.0628910064697  ms


** Avoid For loops to do the calculations, Use Vectorization to do the task **

In [4]:
tic = time.time()
c = np.exp(a)
toc = time.time()
#print(c)
print("Numpy method time: ",str((toc-tic)*1000)," ms")


c = np.zeros((1000000, 1))  # creating zero array
tic = time.time()
for i in range(1000000):
    c[i] = math.exp(a[i])   # looping and calculation exp of value
toc = time.time()
#print(c)
print("For loop method time: ",str((toc-tic)*1000)," ms")

Numpy method time:  14.000654220581055  ms
For loop method time:  718.0147171020508  ms


## Numpy Vector Operations

In [17]:
a = np.random.rand(2,3)
b = np.random.rand(3,4)
c = np.arange(10)
d = np.random.randint(0,100,10)

In [18]:
print(c)
print(d)
c*d  # element wise multiplication

[0 1 2 3 4 5 6 7 8 9]
[73 32 27  4 41 39 78 90 28 26]


array([  0,  32,  54,  12, 164, 195, 468, 630, 224, 234])

In [31]:
e=np.dot(a,b)  # matrix multiplication
print(a)
print(b)
print(e)

[[ 0.40480442  0.2598269   0.6294821 ]
 [ 0.03087543  0.9489524   0.99572218]]
[[ 0.97858683  0.66214331  0.15410432  0.83003073]
 [ 0.77624917  0.41628082  0.1283637   0.63154429]
 [ 0.17809376  0.45958262  0.15700918  0.54641448]]
[[ 0.70993353  0.66549853  0.19456892  0.84405044]
 [ 0.94416971  0.87309125  0.28290659  1.16901004]]


In [32]:
print(np.dot(d.T,c))
print(np.dot(c,d.T))
print(c.shape)
print((d.T).shape)

2013
2013
(10,)
(10,)


In [2]:
print('Hi Kanika')

Hi Kanika


In [3]:
for i in range(3):
    print(i*i)

0
1
4
