In [1]:
#import
import torch
import numpy as np

In [2]:
# uninitialize Tensor
x = torch.Tensor(3,4)
print(x)


1.00000e-43 *
  1.3733  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 3x4]



In [3]:
# Randomly intitialize Tensor
x = torch.rand(3,4)
print(x)


 0.3058  0.5681  0.3270  0.9632
 0.2540  0.1470  0.0311  0.6774
 0.2009  0.4719  0.4170  0.2510
[torch.FloatTensor of size 3x4]



In [4]:
# checking size
x.size()

torch.Size([3, 4])

### Operations

In [5]:
y = torch.rand(3,4)

x+y


 0.5464  0.8071  1.2016  1.7829
 0.4553  0.3868  0.2269  1.4373
 1.0676  1.4457  0.5221  0.2749
[torch.FloatTensor of size 3x4]

In [6]:
print(torch.add(x,y))


 0.5464  0.8071  1.2016  1.7829
 0.4553  0.3868  0.2269  1.4373
 1.0676  1.4457  0.5221  0.2749
[torch.FloatTensor of size 3x4]



In [8]:
# assigning this to variable
z = torch.add(x,y)
print(z)
print(type(z))


 0.5464  0.8071  1.2016  1.7829
 0.4553  0.3868  0.2269  1.4373
 1.0676  1.4457  0.5221  0.2749
[torch.FloatTensor of size 3x4]

<class 'torch.FloatTensor'>


In [9]:
# OR
z = torch.Tensor(3,4)   # initializing a Tensor of 3x4
torch.add(x,y, out=z)
print(z)


 0.5464  0.8071  1.2016  1.7829
 0.4553  0.3868  0.2269  1.4373
 1.0676  1.4457  0.5221  0.2749
[torch.FloatTensor of size 3x4]



In [10]:
# In place addition
print(y)
y.add_(x)
print(y)


 0.2406  0.2390  0.8746  0.8197
 0.2012  0.2397  0.1958  0.7598
 0.8667  0.9738  0.1051  0.0239
[torch.FloatTensor of size 3x4]


 0.5464  0.8071  1.2016  1.7829
 0.4553  0.3868  0.2269  1.4373
 1.0676  1.4457  0.5221  0.2749
[torch.FloatTensor of size 3x4]



### Numpy Bridge  

** From Numpy to Torch Tensor **  

In [11]:
a = np.ones(4)
print(a)
print(type(a))

[ 1.  1.  1.  1.]
<class 'numpy.ndarray'>


In [13]:
a1 = torch.from_numpy(a)
print(a1)
print(type(a1))


 1
 1
 1
 1
[torch.DoubleTensor of size 4]

<class 'torch.DoubleTensor'>


In [14]:
# adding
a=a+1
print(a)
print(a1)

[ 2.  2.  2.  2.]

 1
 1
 1
 1
[torch.DoubleTensor of size 4]



** From Tensor to Numpy **

In [15]:
b = torch.ones(5)
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [16]:
b1 = b.numpy()
print(b1, type(b1))

[ 1.  1.  1.  1.  1.] <class 'numpy.ndarray'>


In [17]:
# adding

b = b+1
print(b, b1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]
 [ 1.  1.  1.  1.  1.]


In [19]:
# in place addition
b.add_(1)
print(b, b1)


 3
 3
 3
 3
 3
[torch.FloatTensor of size 5]
 [ 1.  1.  1.  1.  1.]


** All in one place **

In [20]:
a = torch.ones(6)
b = a.numpy()
print("Initialized a and b")
print("a: ",a, type(a))
print("b: ",b, type(b))

Initialized a and b
a:  
 1
 1
 1
 1
 1
 1
[torch.FloatTensor of size 6]
 <class 'torch.FloatTensor'>
b:  [ 1.  1.  1.  1.  1.  1.] <class 'numpy.ndarray'>


In [21]:
# in place addition to a
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
 2
[torch.FloatTensor of size 6]

[ 2.  2.  2.  2.  2.  2.]


In [22]:
# regular addition to a
a = a+1
print(a)
print(b)


 3
 3
 3
 3
 3
 3
[torch.FloatTensor of size 6]

[ 2.  2.  2.  2.  2.  2.]


In [24]:
c = torch.from_numpy(b)
d=np.add(b, 1)
print(b,type(b))
print(c,type(c))
print(d,type(d))

[ 2.  2.  2.  2.  2.  2.] <class 'numpy.ndarray'>

 2
 2
 2
 2
 2
 2
[torch.FloatTensor of size 6]
 <class 'torch.FloatTensor'>
[ 3.  3.  3.  3.  3.  3.] <class 'numpy.ndarray'>


### Cuda Tensors

In [25]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [26]:
torch.cuda.is_available()

False