### Moving average 

In [2]:
import numpy as np

In [90]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Considering moving average for 4 occurance

In [78]:
def moving_average(a, n=3) :
    '''
    Calculate the moving average for ocuurance n

    a : list like Values
    n : no of occurance
    '''
    a = np.concatenate((np.zeros(n-1), a))
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [79]:
moving_average(a, 4)

array([ 0.25,  0.75,  1.5 ,  2.5 ,  3.5 ,  4.5 ,  5.5 ,  6.5 ,  7.5 ])

In [137]:
def moving_average_exp(data, n=3, bias_correc=False):
    '''
    Calculate the exponential moving average for ocuurance n

    data : list like Values
    n : no of occurance
    bias_correc : Bias correction - True/False
    '''
    frac = (1 - (1/float(n)))

    lis = np.zeros((data.shape[0]+1))
    for idx, val in enumerate(data):
        lis[idx+1] = frac*lis[idx] + (1-frac)*val
    ret = lis[1:]
    
    if bias_correc==True:
        #lis2 = np.zeros(data.shape[0])
        for idx, val in enumerate(ret):
            bc = (1- np.power(frac, idx+1))
            ret[idx] /=  bc
    #ret=lis[:]
                    
    return ret

In [138]:
moving_average_exp(a,4)

array([ 0.25      ,  0.6875    ,  1.265625  ,  1.94921875,  2.71191406,
        3.53393555,  4.40045166,  5.30033875,  6.22525406])

In [139]:
moving_average_exp(a,4, True)

array([ 1.        ,  1.57142857,  2.18918919,  2.85142857,  3.55569782,
        4.2990793 ,  5.07832641,  5.89000424,  6.73062059])

### Choosing Hyperparameter value scale  
* If the no is big enough or > 1 use the linear random search to pick the value  
* else if no is << 1 then use the lograthmic random search to pick the value

In [11]:
# we have to choose the 5 values between 50, 100
val = np.random.randint(50, 100, 5)
print(val)
print(np.mean(val))
print(np.var(val))

[72 67 53 99 62]
70.6
241.04


In [16]:
# we have to choose the 5 values between 0.0001 to 1
p = -4 * np.random.rand(5)
val = np.power(10, p)
print(val)
print(np.mean(val))
print(np.var(val))

[  1.31301917e-04   2.02119497e-01   2.82568112e-04   7.53777981e-04
   4.30560455e-02]
0.0492686380268
0.00611395715421
